#define CRYPTO_VERSION "1.0"
#define CRYPTO_KEYBYTES 16
#define CRYPTO_NSECBYTES 16
#define CRYPTO_NPUBBYTES 16
#define CRYPTO_ABYTES 16
#define CRYPTO_NOOVERLAP 1
#define PSASPIN_AEAD_RATE 16
//#define PSASPIN_AEAD_MLEN 128 
